import Foundation
import Testing
import WWCore
@testable import WWPersistence

@Suite("Edit-map document durability and migration")
struct EditMapPersistenceTests {
    let fixture = AlignmentPersistenceFixture()
    // Frozen schema-3 envelope, never regenerated by the schema-4 encoder.
    let schema3Golden = Data(#"{"checksum":"sha256:85391f798ac816ee7ec9cd44c96865394748f889ca3b76f384f550d465ce1559","format":"com.brandonmartinez.wavewrangler.show","payload":{"episodes":[],"history":{"cursor":0,"entries":[]},"schemaVersion":3,"show":{"id":"00000000-0000-4000-8000-000000000001","notes":"","title":"Schema 3 Show"},"speakers":[]},"publicationID":"00000000-0000-4000-8000-000000000301","revision":7,"schemaVersion":3}"#.utf8)

    @Test func mapAndHistoryRoundTripAsOneValidatedShow() throws {
        var model = fixture.show(with: EpisodeAlignment(maps: [
            try fixture.version(1, map: fixture.map())
        ], acceptedRevision: 1))
        let version = EditMapVersion(
            revision: 1, alignmentRevision: 1,
            sourceIDs: [fixture.host, fixture.guest],
            removals: [EditRemoval(startFrame: 100, endFrame: 200, decisionID: UUID())]
        )
        model = try model.recordingEditMap(version, in: fixture.episodeID, actionName: "Shorten reviewed pause")
        let coder = JSONEnvelopeCoder<ShowDocumentModel>.show
        let bytes = try coder.encode(model, revision: 3)
        #expect(try coder.decode(bytes).payload == model)
        #expect(try coder.decode(bytes).payload.editMaps(for: fixture.episodeID)?.selected == version)

        var invalid = model
        invalid.editMaps[0].selectedRevision = 99
        #expect(throws: PersistenceError.self) { try coder.encode(invalid, revision: 4) }
    }

    @MainActor
    @Test func unrelatedRenamesPreserveSavedChoiceAfterReopenWithoutAuthorizingRead() throws {
        var model = fixture.show(with: EpisodeAlignment(maps: [
            try fixture.version(1, map: fixture.map())
        ], acceptedRevision: 1))
        let version = EditMapVersion(
            revision: 1, alignmentRevision: 1,
            sourceIDs: [fixture.host, fixture.guest],
            removals: [EditRemoval(startFrame: 100, endFrame: 200, decisionID: UUID())]
        )
        model = try model.recordingEditMap(version, in: fixture.episodeID, actionName: "Shorten")
        let renamed = try model.renamingShow(to: "Renamed show")
            .renamingEpisode(fixture.episodeID, to: "Renamed episode")
        let checked = EditMapPublication.revalidated(
            renamed, replacing: model,
            current: { EditMapSnapshot(model: model, serial: 2) }, prove: nil
        )
        #expect(checked.refusal == nil)
        let coder = JSONEnvelopeCoder<ShowDocumentModel>.show
        let bytes = try coder.encode(checked.model, revision: 2)
        let reopened = try coder.decode(bytes).payload
        #expect(reopened.editMaps(for: fixture.episodeID)?.selected == version)
        #expect(reopened.history == model.history)
        #expect(throws: EditMapPublicationError.proofUnavailable) {
            try EditMapPublication.selected(
                in: fixture.episodeID,
                current: { EditMapSnapshot(model: reopened, serial: 3) }, prove: nil
            )
        }
    }

    @Test func schema3OpensReadOnlyAndMigratesWithExactPayloadPreserved() throws {
        let coder = JSONEnvelopeCoder<ShowSchemaMigration.ShowDocumentModelV3>(
            format: ShowSchemaMigration.schema3Format
        ) { _, _ in [] }
        let bytes = schema3Golden
        let old = try coder.decode(bytes).payload
        #expect(old.schemaVersion == 3)
        #expect(throws: PersistenceError.unsupportedOlderSchema(found: 3, minimum: 4)) {
            try JSONEnvelopeCoder<ShowDocumentModel>.show.decode(bytes)
        }
        let upgraded = try ShowSchemaMigration.decodeSchema3(bytes).payload
        #expect(upgraded.editMaps.isEmpty)
        #expect(upgraded.episodes == old.episodes)
        #expect(ShowSchemaMigration.schema3ExpectationFailures(original: bytes, migrated: upgraded).isEmpty)
        #expect(try ShowSchemaMigration.decodeUpgradingOlder(bytes).payload == upgraded)

        let rig = Rig()
        let url = rig.url()
        try bytes.write(to: url)
        let key = DocumentKey.show(old.show.id)
        guard case .needsMigration(fromSchema: 3, fingerprint: _) = DocumentOpener.show(recovery: rig.recovery).open(url, key: key) else {
            Issue.record("schema 3 must open read-only pending an explicit update")
            return
        }
        #expect(try Data(contentsOf: url) == bytes)
        let receipt = try DocumentMigrator.show(publisher: rig.publisher).migrate(url, key: key)
        #expect(try Data(contentsOf: receipt.backup) == bytes)
        #expect(try JSONEnvelopeCoder<ShowDocumentModel>.show.decode(Data(contentsOf: url)).payload == upgraded)
    }

    @Test func schema3ReaderRefusesNewEditAuthorityBeforeDecodingPayload() throws {
        let model = ShowDocumentModel.untitled()
        let bytes = try JSONEnvelopeCoder<ShowDocumentModel>.show.encode(model, revision: 1)
        let reader = JSONEnvelopeCoder<ShowSchemaMigration.ShowDocumentModelV3>(
            format: ShowSchemaMigration.schema3Format
        ) { _, _ in [] }
        #expect(throws: PersistenceError.unknownNewerSchema(found: 4, supported: 3)) {
            try reader.decode(bytes)
        }
        var migrated = try ShowSchemaMigration.decodeSchema3(schema3Golden).payload
        migrated.show.title = "Changed"
        #expect(!ShowSchemaMigration.schema3ExpectationFailures(
            original: schema3Golden, migrated: migrated
        ).isEmpty)
    }

    @Test func schema3AlignmentSurvivesMigrationWithoutAnEditSelection() throws {
        let map = try fixture.version(1, map: fixture.map())
        var episode = fixture.episode
        episode.alignment = EpisodeAlignment(maps: [map], acceptedRevision: 1)
        let old = ShowSchemaMigration.ShowDocumentModelV3(
            schemaVersion: 3, show: fixture.show.show, speakers: [],
            episodes: [episode], history: EditHistory()
        )
        let coder = JSONEnvelopeCoder<ShowSchemaMigration.ShowDocumentModelV3>(
            format: ShowSchemaMigration.schema3Format
        ) { _, _ in [] }
        let bytes = try coder.encode(old, revision: 5)
        let migrated = try ShowSchemaMigration.decodeSchema3(bytes).payload
        #expect(migrated.episode(fixture.episodeID)?.alignment == episode.alignment)
        #expect(migrated.editMaps.isEmpty)
        #expect(ShowSchemaMigration.schema3ExpectationFailures(original: bytes, migrated: migrated).isEmpty)
    }
}
