import Foundation
import Testing
import WWCore
import WWSources
@testable import WWEpisodeSetup

/// Delegates to the real `SystemSourceIO` and counts download requests/progress queries.
final class CountingIO: SourceIO, @unchecked Sendable {
    let base = SystemSourceIO()
    private let lock = NSLock()
    private var _downloads = 0
    var downloads: Int { lock.withLock { _downloads } }
    var provenance: ObservationProvenance { base.provenance }
    func metadata(at url: URL) -> MetadataResult { base.metadata(at: url) }
    func listItems(under directory: URL) -> DirectoryListing { base.listItems(under: directory) }
    func makeReadOnlyBookmark(for url: URL) throws -> Data { try base.makeReadOnlyBookmark(for: url) }
    func resolveBookmark(_ data: Data) -> BookmarkResolution { base.resolveBookmark(data) }
    func startAccessingSecurityScope(_ url: URL) -> Bool { base.startAccessingSecurityScope(url) }
    func stopAccessingSecurityScope(_ url: URL) { base.stopAccessingSecurityScope(url) }
    func requestDownload(of url: URL) throws {
        lock.withLock { _downloads += 1 }
        try base.requestDownload(of: url)
    }
    func downloadFraction(of url: URL) async -> Knowledge<Double> {
        lock.withLock { _downloads += 1 }
        return await base.downloadFraction(of: url)
    }
}

final class FixedPreference: SourceDownloadPreference {
    var downloadsAutomatically: Bool
    init(_ on: Bool) { downloadsAutomatically = on }
}

@MainActor
@Suite("WWSources adapter (synthetic temp files, observed file system)")
struct WWSourcesSetupEngineTests {
    /// Synthetic tree: Rec/ZOOM0001/{tr1.wav,tr2.wav}, Rec/notes.txt, Rec/.hidden — generated bytes only.
    func makeTree() throws -> URL {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appending(path: "ww-setup-\(UUID().uuidString)/Rec")
        try fm.createDirectory(at: root.appending(path: "ZOOM0001"), withIntermediateDirectories: true)
        try Data(repeating: 1, count: 64).write(to: root.appending(path: "ZOOM0001/tr1.wav"))
        try Data(repeating: 2, count: 96).write(to: root.appending(path: "ZOOM0001/tr2.wav"))
        try Data("n".utf8).write(to: root.appending(path: "notes.txt"))
        try Data("h".utf8).write(to: root.appending(path: ".hidden"))
        return root
    }

    func firstSnapshot(_ engine: WWSourcesSetupEngine, _ ids: Set<SourceID>, until: ([SourceID: SourceStatusSnapshot]) -> Bool) async -> [SourceID: SourceStatusSnapshot] {
        var last: [SourceID: SourceStatusSnapshot] = [:]
        for await update in engine.observe(ids) {
            last = update
            if until(update) { break }
        }
        return last
    }

    @Test(.timeLimit(.minutes(1))) func importObserveDeniedAndRelink() async throws {
        let root = try makeTree()
        defer { try? FileManager.default.removeItem(at: root.deletingLastPathComponent()) }
        let io = CountingIO()
        let engine = WWSourcesSetupEngine(showID: ShowID(), store: InMemoryDeviceAccessStore(), context: SourceAccessContext(io: io), preference: FixedPreference(false))

        // Metadata-only scan: two recordings listed; the document and hidden file are only counted.
        let scan = try await engine.scanForImport([root], episodeSourceIDs: [])
        #expect(Set(scan.candidates.map(\.displayName)) == ["tr1.wav", "tr2.wav"])
        #expect(scan.uncountedSkips.notRecordings == 1)
        #expect(scan.uncountedSkips.hidden == 1)
        let review = ImportReview(scan: scan, episodeTitle: "E", knownSpeakerNames: [])
        #expect(review.rows.allSatisfy { $0.group.isUnconfirmedSuggestion || $0.group == .none })
        let items = review.importItems()
        try await engine.commitImport(Dictionary(uniqueKeysWithValues: items.map { ($0.candidateID, $0.item.source.id) }))

        let ids = Set(items.map(\.item.source.id))
        let ready = await firstSnapshot(engine, ids) { $0.count == 2 && $0.values.allSatisfy { $0.location == .known } }
        for snapshot in ready.values {
            #expect(snapshot.access == .granted)
            #expect(snapshot.residency == .local)
            #expect(snapshot.identity == .detailsMatch)
            #expect(snapshot.summary.text == "Ready")
        }
        #expect(io.downloads == 0, "downloads Off: zero download requests or progress queries")

        // chmod 000 on the folder: Access denied, never Not found.
        let folder = root.appending(path: "ZOOM0001")
        try FileManager.default.setAttributes([.posixPermissions: 0o000], ofItemAtPath: folder.path)
        defer { try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: folder.path) }
        await engine.refresh(Array(ids))
        let denied = WWSourcesStatusMapping.snapshot(engine.monitor.observations[ids.first!])
        #expect(denied.summary.text != "Not found", "\(denied)")
        if case .missing = denied.location { Issue.record("denied shown as missing: \(denied)") }
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: folder.path)

        // Move tr2 away: Not found; relink to the moved file needs no default when details differ only by path.
        let tr2ID = try #require(items.first { $0.item.source.displayNameHint == "tr2.wav" }?.item.source.id)
        let moved = root.appending(path: "tr2-moved.wav")
        try FileManager.default.moveItem(at: folder.appending(path: "tr2.wav"), to: moved)
        await engine.refresh([tr2ID])
        let missing = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(["Not found", "Moved"].contains(missing.summary.text), "\(missing)")

        let comparison = await engine.compare(candidate: moved, for: tr2ID)
        #expect(comparison.canConfirm)
        #expect(comparison.rows.first?.result == .different, "the name differs")
        let receipt = try await engine.commitRelink(tr2ID, to: moved, identity: comparison.acceptedIdentity)
        let relinked = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(relinked.location == .known)
        #expect(FileManager.default.fileExists(atPath: moved.path), "the original is never moved or changed")
        try await engine.revertRelink(receipt)
        let reverted = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(reverted.location != .known)
        #expect(io.downloads == 0)
    }

    @Test func mappingIsHonest() {
        #expect(WWSourcesStatusMapping.transfer(.offlineOrUnknown(nil)) == .failed(reason: "no progress was reported"))
        #expect(WWSourcesStatusMapping.transfer(.offlineOrUnknown(nil)).presentation.summaryText != "No connection")
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.availabilityOff)) == .downloadsOff)
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.unsupportedLocation)) == .unsupportedLocation)
        #expect(WWSourcesStatusMapping.transfer(.requested) == .downloading(fraction: nil))
        #expect(WWSourcesStatusMapping.transfer(.inProgress(fractionCompleted: .unknown)) == .downloading(fraction: nil))
        #expect(WWSourcesStatusMapping.transfer(.inProgress(fractionCompleted: .known(0.5))) == .downloading(fraction: 0.5))
        let denied = AvailabilityObservation(observedAt: Date(), location: .unknown, access: .denied)
        #expect(WWSourcesStatusMapping.snapshot(denied).summary.text == "Access denied")
        #expect(WWSourcesStatusMapping.snapshot(nil) == .checking)
        #expect(WWSourcesStatusMapping.identity(.changed([.fileSize])) == .changed(differences: "size differ", acceptedByUser: false))
        #expect(WWSourcesStatusMapping.identity(.mismatch([.fileIdentifier])) == .mismatch(differences: "file id differ"))
        #expect(WWSourcesStatusMapping.residency(.downloading) == .cloudOnly)
        let missing = AvailabilityObservation(observedAt: Date(), location: .missing(lastKnownPathOccupied: .known(true)), access: .granted)
        #expect(WWSourcesStatusMapping.snapshot(missing).location == .missing(sameNamedFileAtOriginalLocation: true))
    }
}
