import Foundation
import Testing
import WWCore
import WWSources
@testable import WWEpisodeSetup

/// Delegates to the real `SystemSourceIO` and counts download requests/progress queries.
final class CountingIO: SourceIO, @unchecked Sendable {
    let base = SystemSourceIO()
    private let lock = NSLock()
    private var _downloads = 0
    var downloads: Int { lock.withLock { _downloads } }
    var provenance: ObservationProvenance { base.provenance }
    func metadata(at url: URL) -> MetadataResult { base.metadata(at: url) }
    func listItems(under directory: URL) -> DirectoryListing { base.listItems(under: directory) }
    func makeReadOnlyBookmark(for url: URL) throws -> Data { try base.makeReadOnlyBookmark(for: url) }
    func resolveBookmark(_ data: Data) -> BookmarkResolution { base.resolveBookmark(data) }
    func startAccessingSecurityScope(_ url: URL) -> Bool { base.startAccessingSecurityScope(url) }
    func stopAccessingSecurityScope(_ url: URL) { base.stopAccessingSecurityScope(url) }
    func requestDownload(of url: URL) throws {
        lock.withLock { _downloads += 1 }
        try base.requestDownload(of: url)
    }
    func downloadFraction(of url: URL) async -> Knowledge<Double> {
        lock.withLock { _downloads += 1 }
        return await base.downloadFraction(of: url)
    }
}

@MainActor
final class FixedPreference: @MainActor SourceDownloadPreference {
    var downloadsAutomatically: Bool
    init(_ on: Bool) { downloadsAutomatically = on }
}

@MainActor
@Suite("WWSources adapter (synthetic temp files, observed file system)")
struct WWSourcesSetupEngineTests {
    /// Synthetic tree: Rec/ZOOM0001/{tr1.wav,tr2.wav}, Rec/notes.txt, Rec/.hidden — generated bytes only.
    func makeTree() throws -> URL {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appending(path: "ww-setup-\(UUID().uuidString)/Rec")
        try fm.createDirectory(at: root.appending(path: "ZOOM0001"), withIntermediateDirectories: true)
        try Data(repeating: 1, count: 64).write(to: root.appending(path: "ZOOM0001/tr1.wav"))
        try Data(repeating: 2, count: 96).write(to: root.appending(path: "ZOOM0001/tr2.wav"))
        try Data("n".utf8).write(to: root.appending(path: "notes.txt"))
        try Data("h".utf8).write(to: root.appending(path: ".hidden"))
        return root
    }

    func firstSnapshot(_ engine: WWSourcesSetupEngine, _ ids: Set<SourceID>, until: ([SourceID: SourceStatusSnapshot]) -> Bool) async -> [SourceID: SourceStatusSnapshot] {
        var last: [SourceID: SourceStatusSnapshot] = [:]
        for await update in engine.observe(ids) {
            last = update
            if until(update) { break }
        }
        return last
    }

    @Test(.timeLimit(.minutes(1))) func importObserveDeniedAndRelink() async throws {
        let root = try makeTree()
        defer { try? FileManager.default.removeItem(at: root.deletingLastPathComponent()) }
        let io = CountingIO()
        let engine = WWSourcesSetupEngine(showID: ShowID(), store: InMemoryDeviceAccessStore(), context: SourceAccessContext(io: io), preference: FixedPreference(false))

        // Metadata-only scan: two recordings listed; the document and hidden file are only counted.
        let scan = try await engine.scanForImport([root], episodeSourceIDs: [])
        #expect(Set(scan.candidates.map(\.displayName)) == ["tr1.wav", "tr2.wav"])
        #expect(scan.uncountedSkips.notRecordings == 1)
        #expect(scan.uncountedSkips.hidden == 1)
        let review = ImportReview(scan: scan, episodeTitle: "E", knownSpeakerNames: [])
        #expect(review.rows.allSatisfy { $0.group.isUnconfirmedSuggestion || $0.group == .none })
        let items = review.importItems()
        try await engine.commitImport(Dictionary(uniqueKeysWithValues: items.map { ($0.candidateID, $0.item.source.id) }), fromScan: review.scanToken)

        let ids = Set(items.map(\.item.source.id))
        let ready = await firstSnapshot(engine, ids) { $0.count == 2 && $0.values.allSatisfy { $0.location == .known } }
        for snapshot in ready.values {
            #expect(snapshot.access == .granted)
            #expect(snapshot.residency == .local)
            #expect(snapshot.identity == .detailsMatch)
            #expect(snapshot.summary.text == "Ready")
        }
        #expect(io.downloads == 0, "downloads Off: zero download requests or progress queries")

        // chmod 000 on the folder: Access denied, never Not found.
        let folder = root.appending(path: "ZOOM0001")
        try FileManager.default.setAttributes([.posixPermissions: 0o000], ofItemAtPath: folder.path)
        defer { try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: folder.path) }
        await engine.refresh(Array(ids))
        for id in ids {
            let denied = WWSourcesStatusMapping.snapshot(engine.monitor.observations[id])
            #expect(denied.access == .denied, "\(denied)")
            #expect(denied.summary.text == "Access denied", "\(denied)")
            if case .missing = denied.location { Issue.record("denied shown as missing: \(denied)") }
        }
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: folder.path)

        // Move tr2 away: Not found; relink to the moved file needs no default when details differ only by path.
        let tr2ID = try #require(items.first { $0.item.source.displayNameHint == "tr2.wav" }?.item.source.id)
        let moved = root.appending(path: "tr2-moved.wav")
        try FileManager.default.moveItem(at: folder.appending(path: "tr2.wav"), to: moved)
        await engine.refresh([tr2ID])
        let missing = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(["Not found", "Moved"].contains(missing.summary.text), "\(missing)")

        let comparison = await engine.compare(candidate: moved, for: tr2ID)
        #expect(comparison.canConfirm)
        #expect(comparison.rows.first?.result == .different, "the name differs")
        let receipt = try await engine.commitRelink(tr2ID, to: moved, identity: comparison.acceptedIdentity)
        let relinked = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(relinked.location == .known)
        #expect(FileManager.default.fileExists(atPath: moved.path), "the original is never moved or changed")
        try await engine.revertRelink(receipt)
        let reverted = WWSourcesStatusMapping.snapshot(engine.monitor.observations[tr2ID])
        #expect(reverted.location != .known)
        #expect(io.downloads == 0)
    }

    @Test(.timeLimit(.minutes(1))) func concurrentScansCommitTheirOwnRecords() async throws {
        let first = try makeTree()
        let second = try makeTree()
        defer {
            try? FileManager.default.removeItem(at: first.deletingLastPathComponent())
            try? FileManager.default.removeItem(at: second.deletingLastPathComponent())
        }
        let store = InMemoryDeviceAccessStore()
        let showID = ShowID()
        let engine = WWSourcesSetupEngine(showID: showID, store: store, context: SourceAccessContext(io: CountingIO()), preference: FixedPreference(false))
        // Window A scans, then window B scans before A imports.
        let scanA = try await engine.scanForImport([first], episodeSourceIDs: [])
        let scanB = try await engine.scanForImport([second], episodeSourceIDs: [])
        let itemsA = ImportReview(scan: scanA, episodeTitle: "A", knownSpeakerNames: []).importItems()
        try await engine.commitImport(Dictionary(uniqueKeysWithValues: itemsA.map { ($0.candidateID, $0.item.source.id) }), fromScan: scanA.token)
        let records = await store.records(in: showID)
        #expect(Set(records.map(\.sourceID)) == Set(itemsA.map(\.item.source.id)), "A's commit used A's plan")
        // The same scan can't be committed twice, and an unknown source has no record.
        await #expect(throws: SourceEngineError.self) {
            try await engine.commitImport([:], fromScan: scanA.token)
        }
        await #expect(throws: SourceEngineError.self) {
            try await engine.commitImport([UUID(): SourceID()], fromScan: scanB.token)
        }
    }

    /// Reviewer's probe: observe, cancel the consumer, shut down, drop the engine — nothing keeps it alive.
    @Test(.timeLimit(.minutes(1))) func observingNeverLeaksTheEngine() async throws {
        let root = try makeTree()
        defer { try? FileManager.default.removeItem(at: root.deletingLastPathComponent()) }
        var engine: WWSourcesSetupEngine? = WWSourcesSetupEngine(showID: ShowID(), store: InMemoryDeviceAccessStore(), context: SourceAccessContext(io: CountingIO()), preference: FixedPreference(false))
        weak let weakEngine = engine
        let scan = try await engine!.scanForImport([root], episodeSourceIDs: [])
        let review = ImportReview(scan: scan, episodeTitle: "E", knownSpeakerNames: [])
        let items = review.importItems()
        try await engine!.commitImport(Dictionary(uniqueKeysWithValues: items.map { ($0.candidateID, $0.item.source.id) }), fromScan: scan.token)
        let stream = engine!.observe(Set(items.map(\.item.source.id)))
        let received = Counter()
        let consumer = Task { for await _ in stream { received.increment() } }
        while received.value < 1 { await Task.yield() }
        consumer.cancel()
        await consumer.value
        #expect(received.value >= 1)
        await engine!.shutdown()
        engine = nil
        for _ in 0..<200 where weakEngine != nil { await Task.yield() }
        #expect(weakEngine == nil, "engine leaked after observe + cancel + shutdown")
    }

    /// Shutdown also finishes streams whose consumer is still listening, then the engine can go away.
    @Test(.timeLimit(.minutes(1))) func shutdownFinishesOpenStreams() async {
        var engine: WWSourcesSetupEngine? = WWSourcesSetupEngine(showID: ShowID(), store: InMemoryDeviceAccessStore(), preference: FixedPreference(false))
        weak let weakEngine = engine
        let stream = engine!.observe([SourceID()])
        let consumer = Task { for await _ in stream {}; return true }
        await Task.yield()
        await engine!.shutdown()
        #expect(await consumer.value, "stream finished by shutdown")
        engine = nil
        for _ in 0..<200 where weakEngine != nil { await Task.yield() }
        #expect(weakEngine == nil)
    }

    /// Shutdown waits for an in-flight refresh before stopping the monitor, and nothing runs after it.
    @Test(.timeLimit(.minutes(1))) func shutdownAwaitsInFlightWork() async throws {
        let root = try makeTree()
        defer { try? FileManager.default.removeItem(at: root.deletingLastPathComponent()) }
        let io = CountingIO()
        let store = GatedDeviceAccessStore()
        let engine = WWSourcesSetupEngine(showID: ShowID(), store: store, context: SourceAccessContext(io: io), preference: FixedPreference(true))
        let scan = try await engine.scanForImport([root], episodeSourceIDs: [])
        let items = ImportReview(scan: scan, episodeTitle: "E", knownSpeakerNames: []).importItems()
        try await engine.commitImport(Dictionary(uniqueKeysWithValues: items.map { ($0.candidateID, $0.item.source.id) }), fromScan: scan.token)
        await store.arm()
        let refresh = Task { await engine.refresh(items.map(\.item.source.id)) }
        while await !store.entered { await Task.yield() }
        let shutdown = Task { await engine.shutdown() }
        for _ in 0..<50 { await Task.yield() }
        #expect(!engine.monitor.isStopped, "shutdown waits for the in-flight refresh")
        await store.release()
        await refresh.value
        await shutdown.value
        #expect(engine.monitor.isStopped)
        await engine.perform(.download, on: items[0].item.source.id)
        await engine.refresh(items.map(\.item.source.id))
        #expect(io.downloads == 0, "no transfer requested after shutdown")
    }

    @Test func leasesArePerOwner() async {
        let made = InMemorySourceSetupEngine()
        let registry = SetupEngineRegistry<ShowID> { _ in made }
        let leases = SetupEngineLeases<Int, ShowID>(registry: registry)
        let show = ShowID()
        let a = await leases.engine(for: 1, key: show)
        let again = await leases.engine(for: 1, key: show)
        #expect(a === again)
        #expect(registry.count(for: show) == 1, "re-leasing from the same window is free")
        _ = await leases.engine(for: 2, key: show)
        #expect(registry.count(for: show) == 2)
        await leases.end(1)
        #expect(!made.calls.contains(.shutdown), "the other window still holds it")
        await leases.end(2)
        #expect(made.calls.contains(.shutdown))
        await leases.end(2)
        #expect(registry.count(for: show) == 0)
    }

    @Test func shutdownStopsFollowingTheDownloadPreference() async {
        let preference = FixedPreference(false)
        let engine = WWSourcesSetupEngine(showID: ShowID(), store: InMemoryDeviceAccessStore(), preference: preference)
        #expect(engine.monitor.setting == .off)
        await engine.shutdown()
        #expect(!engine.isRunning)
        preference.downloadsAutomatically = true
        engine.syncSetting()
        NotificationCenter.default.post(name: UserDefaults.didChangeNotification, object: nil)
        await Task.yield()
        #expect(engine.monitor.setting == .off, "a closed show never turns its downloads on")
    }

    @Test func registrySharesAndShutsDownOnLastRelease() async {
        let engines = [ShowID(), ShowID()].map { ($0, InMemorySourceSetupEngine()) }
        let registry = SetupEngineRegistry<ShowID> { key in engines.first { $0.0 == key }!.1 }
        let (show, engine) = engines[0]
        let a = registry.acquire(show)
        let b = registry.acquire(show)
        #expect(a === b)
        #expect(registry.count(for: show) == 2)
        await registry.release(show)
        #expect(!engine.calls.contains(.shutdown), "another window still uses it")
        await registry.release(show)
        #expect(engine.calls.contains(.shutdown))
        #expect(registry.count(for: show) == 0)
    }

    @Test func awaitingAccessIsNotADownload() {
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.awaitingAccess)) == .idle)
        let observation = AvailabilityObservation(observedAt: Date(), location: .present, access: .needsRegrant, residency: .cloudPlaceholder, transfer: .notRequested(.awaitingAccess))
        let waiting = WWSourcesStatusMapping.snapshot(observation)
        #expect(!waiting.transfer.isActive)
        #expect(EpisodeDownloadProgress(statuses: [waiting]) == nil, "no episode download spinner")
        #expect(!TransferAction.available(transfer: waiting.transfer, residency: waiting.residency, pauseSupported: false).contains(.cancel))
        #expect(waiting.summary.text == "Needs permission")
        // After regrant the transfer stays idle and the file is still in the cloud: no "Downloaded".
        var regranted = observation
        regranted.access = .granted
        regranted.transfer = .idle
        #expect(TransferAnnouncement.decide(from: waiting, to: WWSourcesStatusMapping.snapshot(regranted)) == nil)
    }

    @Test func downloadedIsAnnouncedOnlyWhenTheFileArrived() {
        let downloading = SourceStatusSnapshot(location: .known, access: .granted, residency: .cloudOnly, transfer: .downloading(fraction: nil), identity: .notChecked)
        var arrived = downloading
        arrived.transfer = .idle
        arrived.residency = .local
        #expect(TransferAnnouncement.decide(from: downloading, to: arrived) == .downloaded)
        var stillCloud = downloading
        stillCloud.transfer = .idle
        #expect(TransferAnnouncement.decide(from: downloading, to: stillCloud) == nil)
        var queued = downloading
        queued.transfer = .queued
        #expect(TransferAnnouncement.decide(from: SourceStatusSnapshot(location: .known, access: .granted, residency: .cloudOnly, transfer: .idle, identity: .notChecked), to: queued) == .started)
        var failed = downloading
        failed.transfer = .failed(reason: "no progress was reported")
        #expect(TransferAnnouncement.decide(from: downloading, to: failed)?.text(for: "tr2.wav") == "Download failed for tr2.wav: no progress was reported")
    }

    @Test func mappingIsHonest() {
        #expect(WWSourcesStatusMapping.transfer(.offlineOrUnknown(nil)) == .failed(reason: "no progress was reported"))
        #expect(WWSourcesStatusMapping.transfer(.offlineOrUnknown(nil)).presentation.summaryText != "No connection")
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.availabilityOff)) == .downloadsOff)
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.unsupportedLocation)) == .unsupportedLocation)
        #expect(WWSourcesStatusMapping.transfer(.notRequested(.awaitingAccess)) == .idle)
        #expect(WWSourcesStatusMapping.transfer(.requested) == .downloading(fraction: nil))
        #expect(WWSourcesStatusMapping.transfer(.inProgress(fractionCompleted: .unknown)) == .downloading(fraction: nil))
        #expect(WWSourcesStatusMapping.transfer(.inProgress(fractionCompleted: .known(0.5))) == .downloading(fraction: 0.5))
        let denied = AvailabilityObservation(observedAt: Date(), location: .unknown, access: .denied)
        #expect(WWSourcesStatusMapping.snapshot(denied).summary.text == "Access denied")
        #expect(WWSourcesStatusMapping.snapshot(nil) == .checking)
        #expect(WWSourcesStatusMapping.identity(.changed([.fileSize])) == .changed(differences: "size differ", acceptedByUser: false))
        #expect(WWSourcesStatusMapping.identity(.mismatch([.fileIdentifier])) == .mismatch(differences: "file id differ"))
        #expect(WWSourcesStatusMapping.residency(.downloading) == .cloudOnly)
        let missing = AvailabilityObservation(observedAt: Date(), location: .missing(lastKnownPathOccupied: .known(true)), access: .granted)
        #expect(WWSourcesStatusMapping.snapshot(missing).location == .missing(sameNamedFileAtOriginalLocation: true))
    }
}

final class Counter: @unchecked Sendable {
    private let lock = NSLock()
    private var count = 0
    func increment() { lock.withLock { count += 1 } }
    var value: Int { lock.withLock { count } }
}

/// Wraps an in-memory store; an armed gate *suspends* (never blocks a thread) the next `record(for:)`
/// until released, so tests can hold a refresh in flight without starving the cooperative pool.
actor GatedDeviceAccessStore: DeviceAccessStore {
    private let base: InMemoryDeviceAccessStore
    private var armed = false
    private var waiting: CheckedContinuation<Void, Never>?
    private(set) var entered = false

    init(_ records: [DeviceAccessRecord] = []) {
        base = InMemoryDeviceAccessStore(records)
    }

    func arm() { armed = true; entered = false }

    func release() {
        armed = false
        waiting?.resume()
        waiting = nil
    }

    func record(for key: DeviceAccessKey) async throws -> DeviceAccessRecord? {
        if armed {
            armed = false
            entered = true
            await withCheckedContinuation { waiting = $0 }
        }
        return await base.record(for: key)
    }

    func records(in showID: ShowID) async throws -> [DeviceAccessRecord] { await base.records(in: showID) }
    func allRecords() async throws -> [DeviceAccessRecord] { await base.allRecords() }
    func save(_ record: DeviceAccessRecord) async throws { await base.save(record) }
    func save(_ records: [DeviceAccessRecord]) async throws { await base.save(records) }
    func removeRecord(for key: DeviceAccessKey) async throws { await base.removeRecord(for: key) }
    func removeRecords(in showID: ShowID) async throws { await base.removeRecords(in: showID) }
}
