import Accelerate
import AudioToolbox
import CryptoKit
import Foundation
import Testing
import WWCore
import WWSources
@testable import WWDecode

// Synthetic fixtures only: every file here is generated by these helpers under $TMPDIR.

// MARK: - Deterministic signal with planted landmarks

struct SplitMix64 {
    var state: UInt64
    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }

    /// Uniform in [-1, 1).
    mutating func unit() -> Double { Double(next() >> 11) / Double(1 << 52) - 1 }
}

/// Planar test signal: low-level noise everywhere plus three Hann-windowed chirp bursts per channel at
/// known source frames. Every sample is `k / 32768` with `|k| < 32768`, so 16/20/24/32-bit integer,
/// 32/64-bit float and lossless encodings all hold it exactly.
struct LandmarkSignal {
    static let burstLength = 1024
    let frames: Int
    let channels: [[Float]]
    /// `landmarks[c]` = source frames where channel `c`'s bursts begin.
    let landmarks: [[Int]]
    /// `bursts[c][k]` = the exact samples of channel `c`'s burst `k`.
    let bursts: [[[Float]]]

    init(frames: Int = 23_456, channelCount: Int, seed: UInt64) {
        self.frames = frames
        var rng = SplitMix64(state: seed)
        var channels: [[Float]] = []
        var landmarks: [[Int]] = []
        var bursts: [[[Float]]] = []
        for c in 0..<channelCount {
            var samples = (0..<frames).map { _ in Self.quantize(0.01 * rng.unit()) }
            let starts = [600 + 13 * c, frames / 3 + 211 * c, frames - 2000 - 37 * c]
            precondition(zip(starts, starts.dropFirst()).allSatisfy { $0 + Self.burstLength <= $1 }, "LandmarkSignal(frames: \(frames)) is too short for channel \(c)'s bursts")
            // A Hann-windowed chirp with a per-channel band, direction and phase: a sharp correlation peak
            // that lossy codecs preserve, and a different position per channel so a swap shows as a lag.
            let low = 0.03 + 0.004 * Double(c)
            let high = 0.18 + 0.01 * Double(c)
            let (f0, f1) = c % 2 == 0 ? (low, high) : (high, low)
            let phase = Double.pi * rng.unit()
            let length = Double(Self.burstLength)
            var burst: [Float] = []
            for i in 0..<Self.burstLength {
                let t = Double(i)
                let window = 0.5 - 0.5 * cos(2 * Double.pi * t / (length - 1))
                burst.append(Self.quantize(0.5 * window * sin(2 * Double.pi * (f0 * t + (f1 - f0) * t * t / (2 * length)) + phase)))
            }
            var channelBursts: [[Float]] = []
            for start in starts {
                samples.replaceSubrange(start ..< start + Self.burstLength, with: burst)
                channelBursts.append(burst)
            }
            channels.append(samples)
            landmarks.append(starts)
            bursts.append(channelBursts)
        }
        self.channels = channels
        self.landmarks = landmarks
        self.bursts = bursts
    }

    static func quantize(_ value: Double) -> Float {
        Float((value * 32768).rounded().clamped(-32767, 32767) / 32768)
    }

    /// The lag (decoded − truth) of the strongest correlation between `burst` and `decoded` around
    /// `truth`, searched over ±`window` frames, and the normalized correlation at that lag.
    static func locate(_ burst: [Float], in decoded: [Float], near truth: Int, window: Int = 3000) -> (lag: Int, correlation: Float) {
        let low = max(0, truth - window)
        let high = min(decoded.count - burst.count, truth + window)
        guard high >= low else { return (Int.max, 0) }
        let lags = high - low + 1
        var output = [Float](repeating: 0, count: lags)
        decoded.withUnsafeBufferPointer { signal in
            burst.withUnsafeBufferPointer { filter in
                vDSP_conv(signal.baseAddress! + low, 1, filter.baseAddress!, 1, &output, 1, vDSP_Length(lags), vDSP_Length(burst.count))
            }
        }
        var peak: Float = 0
        var index: vDSP_Length = 0
        vDSP_maxvi(output, 1, &peak, &index, vDSP_Length(lags))
        let start = low + Int(index)
        var burstEnergy: Float = 0
        var segmentEnergy: Float = 0
        vDSP_svesq(burst, 1, &burstEnergy, vDSP_Length(burst.count))
        decoded.withUnsafeBufferPointer { vDSP_svesq($0.baseAddress! + start, 1, &segmentEnergy, vDSP_Length(burst.count)) }
        let norm = (burstEnergy * segmentEnergy).squareRoot()
        return (start - truth, norm > 0 ? peak / norm : 0)
    }
}

extension Double {
    func clamped(_ low: Double, _ high: Double) -> Double { Swift.min(Swift.max(self, low), high) }
}

// MARK: - Fixture specifications and writer

struct FixtureSpec: Sendable, CustomTestStringConvertible {
    var container: ContainerKind
    var codec: CodecKind
    var sampleFormat: SourceSampleFormat
    var sampleRate: Int
    var channelCount: Int
    /// Planted out-of-envelope fixtures: write this file type / format / extension instead.
    var fileTypeOverride: AudioFileTypeID? = nil
    var formatOverride: AudioStreamBasicDescription? = nil
    var extensionOverride: String? = nil

    var testDescription: String {
        "\(container.rawValue)/\(codec.rawValue) \(sampleFormat) \(sampleRate) Hz \(channelCount) ch"
    }

    var fileType: AudioFileTypeID {
        if let fileTypeOverride { return fileTypeOverride }
        return switch container {
        case .wave: kAudioFileWAVEType
        case .aiff: kAudioFileAIFFType
        case .aifc: kAudioFileAIFCType
        case .caf: kAudioFileCAFType
        case .m4a: kAudioFileM4AType
        case .flac: kAudioFileFLACType
        }
    }

    var fileExtension: String {
        if let extensionOverride { return extensionOverride }
        return switch container {
        case .wave: "wav"
        case .aiff: "aiff"
        case .aifc: "aifc"
        case .caf: "caf"
        case .m4a: "m4a"
        case .flac: "flac"
        }
    }

    var fileFormat: AudioStreamBasicDescription {
        if let formatOverride { return formatOverride }
        var format = AudioStreamBasicDescription()
        format.mSampleRate = Double(sampleRate)
        format.mChannelsPerFrame = UInt32(channelCount)
        switch codec {
        case .linearPCM:
            let bits = UInt32(sampleFormat.bitsPerSample!)
            format.mFormatID = kAudioFormatLinearPCM
            format.mFormatFlags = kAudioFormatFlagIsPacked
                | (sampleFormat.encoding == .floatingPoint ? kAudioFormatFlagIsFloat : kAudioFormatFlagIsSignedInteger)
                | (sampleFormat.isBigEndian == true ? kAudioFormatFlagIsBigEndian : 0)
            format.mBitsPerChannel = bits
            format.mBytesPerFrame = bits / 8 * UInt32(channelCount)
            format.mFramesPerPacket = 1
            format.mBytesPerPacket = format.mBytesPerFrame
        case .appleLossless, .flac:
            format.mFormatID = codec == .flac ? kAudioFormatFLAC : kAudioFormatAppleLossless
            format.mFormatFlags = switch sampleFormat.bitsPerSample! {
            case 16: 1
            case 20: 2
            case 24: 3
            default: 4
            }
        case .aac:
            format.mFormatID = kAudioFormatMPEG4AAC
        case .opus:
            format.mFormatID = kAudioFormatOpus
        }
        return format
    }

    /// Layout to declare when writing (multichannel coded formats need one). AAC uses layouts without
    /// an LFE channel, whose low-pass would remove the landmark bursts.
    var writeLayout: AudioChannelLayoutTag? {
        switch (codec, channelCount) {
        case (.linearPCM, _): nil
        case (_, 1): kAudioChannelLayoutTag_Mono
        case (_, 2): kAudioChannelLayoutTag_Stereo
        case (.aac, 6): kAudioChannelLayoutTag_AAC_6_0
        case (.aac, 8): kAudioChannelLayoutTag_AAC_Octagonal
        case (_, 6): kAudioChannelLayoutTag_MPEG_5_1_A
        case (_, 8): kAudioChannelLayoutTag_MPEG_7_1_A
        default: nil
        }
    }

    /// Whether the decode must reproduce the written samples bit for bit.
    var isExact: Bool { codec != .aac && codec != .opus }
}

enum FixtureError: Error, CustomStringConvertible {
    case audioToolbox(String, OSStatus)
    var description: String {
        switch self {
        case let .audioToolbox(step, status): "\(step) failed: \(status) '\(FourCharacterCode.string(UInt32(bitPattern: status)))'"
        }
    }
}

final class FixtureDirectory: @unchecked Sendable {
    let url: URL

    init(_ label: String = "fixtures") throws {
        url = FileManager.default.temporaryDirectory
            .appendingPathComponent("wwdecode-tests", isDirectory: true)
            .appendingPathComponent("\(label)-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    }

    deinit {
        // Fixtures are made read-only; restore write permission so they can be removed.
        if let items = FileManager.default.enumerator(at: url, includingPropertiesForKeys: nil) {
            for case let item as URL in items { chmod(item.path, 0o644) }
        }
        try? FileManager.default.removeItem(at: url)
    }

    func file(_ name: String) -> URL { url.appendingPathComponent(name) }

    /// Writes `signal` in `spec`'s format, then makes the file read-only (0444).
    @discardableResult
    func write(_ spec: FixtureSpec, signal: LandmarkSignal, name: String? = nil) throws -> URL {
        let url = file(name ?? "\(UUID().uuidString).\(spec.fileExtension)")
        try Self.encode(spec, signal: signal, to: url)
        chmod(url.path, 0o444)
        return url
    }

    private static func encode(_ spec: FixtureSpec, signal: LandmarkSignal, to url: URL) throws {
        var format = spec.fileFormat
        var created: ExtAudioFileRef?
        var status = ExtAudioFileCreateWithURL(url as CFURL, spec.fileType, &format, nil, AudioFileFlags.eraseFile.rawValue, &created)
        guard status == noErr, let ext = created else { throw FixtureError.audioToolbox("create \(spec.testDescription)", status) }
        defer { ExtAudioFileDispose(ext) }
        if let tag = spec.writeLayout {
            var layout = AudioChannelLayout()
            layout.mChannelLayoutTag = tag
            status = ExtAudioFileSetProperty(ext, kExtAudioFileProperty_FileChannelLayout, UInt32(MemoryLayout<AudioChannelLayout>.size), &layout)
            guard status == noErr else { throw FixtureError.audioToolbox("layout \(spec.testDescription)", status) }
        }
        // Integer PCM is written from 32-bit integers: the platform's float-to-big-endian-int32 encoder
        // rounds negative values 1 LSB low, which would make the file differ from the intended truth.
        let integerClient = spec.codec == .linearPCM && spec.sampleFormat.encoding == .signedInteger && spec.formatOverride == nil
        var client = AudioStreamBasicDescription(
            mSampleRate: Double(spec.sampleRate),
            mFormatID: kAudioFormatLinearPCM,
            mFormatFlags: (integerClient ? kAudioFormatFlagIsSignedInteger : kAudioFormatFlagIsFloat) | kAudioFormatFlagIsNonInterleaved | kAudioFormatFlagIsPacked | kAudioFormatFlagsNativeEndian,
            mBytesPerPacket: 4, mFramesPerPacket: 1, mBytesPerFrame: 4,
            mChannelsPerFrame: UInt32(spec.channelCount), mBitsPerChannel: 32, mReserved: 0
        )
        status = ExtAudioFileSetProperty(ext, kExtAudioFileProperty_ClientDataFormat, UInt32(MemoryLayout.size(ofValue: client)), &client)
        guard status == noErr else { throw FixtureError.audioToolbox("client format \(spec.testDescription)", status) }

        let block = 4096
        let channelCount = signal.channels.count
        let scratch = UnsafeMutablePointer<UInt32>.allocate(capacity: block * channelCount)
        defer { scratch.deallocate() }
        let list = AudioBufferList.allocate(maximumBuffers: channelCount)
        defer { free(list.unsafeMutablePointer) }
        var position = 0
        while position < signal.frames {
            let count = min(block, signal.frames - position)
            for c in 0..<channelCount {
                let destination = scratch + c * block
                for i in 0..<count {
                    let sample = signal.channels[c][position + i]
                    // Every sample is k / 32768, so k << 16 is the exact 32-bit integer.
                    destination[i] = integerClient ? UInt32(bitPattern: Int32((sample * 32768).rounded()) << 16) : sample.bitPattern
                }
                list[c] = AudioBuffer(mNumberChannels: 1, mDataByteSize: UInt32(count * 4), mData: destination)
            }
            status = ExtAudioFileWrite(ext, UInt32(count), list.unsafeMutablePointer)
            guard status == noErr else { throw FixtureError.audioToolbox("write \(spec.testDescription)", status) }
            position += count
        }
    }

    /// Copies `source` to `name` (writable), returning the new URL.
    func copy(_ source: URL, as name: String) throws -> URL {
        let destination = file(name)
        let data = try Data(contentsOf: source)
        try data.write(to: destination)
        return destination
    }

    func writeBytes(_ bytes: Data, as name: String) throws -> URL {
        let destination = file(name)
        try bytes.write(to: destination)
        chmod(destination.path, 0o444)
        return destination
    }
}

// MARK: - Immutability evidence

struct FileSnapshot: Equatable {
    let sha256: String
    let size: Int64
    let modificationSeconds: Int
    let modificationNanoseconds: Int
    let inode: UInt64
    let mode: UInt16

    init(_ url: URL) throws {
        let data = try Data(contentsOf: url)
        sha256 = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
        var info = stat()
        guard lstat(url.path, &info) == 0 else { throw POSIXError(.init(rawValue: errno) ?? .EIO) }
        size = Int64(info.st_size)
        modificationSeconds = info.st_mtimespec.tv_sec
        modificationNanoseconds = info.st_mtimespec.tv_nsec
        inode = UInt64(info.st_ino)
        mode = info.st_mode
    }
}

// MARK: - Sinks

struct CollectedAudio: Sendable, Equatable {
    var channels: [[Float]]
    var chunkSizes: [Int]
}

enum SinkProbeError: Error { case refused }

/// Collects every chunk, checking that chunks are contiguous, in order and within the chunk size.
struct CollectingSink: DecodedAudioSink {
    let channelCount: Int
    var maximumChunk: Int = .max
    var channels: [[Float]]
    var chunkSizes: [Int] = []
    var failAfterChunks: Int?

    init(channelCount: Int, maximumChunk: Int = .max, failAfterChunks: Int? = nil) {
        self.channelCount = channelCount
        self.maximumChunk = maximumChunk
        self.failAfterChunks = failAfterChunks
        channels = Array(repeating: [], count: channelCount)
    }

    mutating func append(_ chunk: DecodedChunk) throws {
        precondition(chunk.channelCount == channelCount, "channel count changed")
        precondition(chunk.firstSourceFrame == Int64(channels[0].count), "chunks must be contiguous")
        precondition(chunk.frameCount > 0 && chunk.frameCount <= maximumChunk, "chunk exceeds the configured size")
        if let limit = failAfterChunks, chunkSizes.count >= limit { throw SinkProbeError.refused }
        for c in 0..<channelCount { channels[c].append(contentsOf: chunk.channel(c)) }
        chunkSizes.append(chunk.frameCount)
    }

    mutating func finish() throws -> CollectedAudio {
        CollectedAudio(channels: channels, chunkSizes: chunkSizes)
    }
}

/// Records the sink lifecycle so tests can prove that failures abandon and never finish.
final class SinkJournal: @unchecked Sendable {
    private let lock = NSLock()
    private var _events: [String] = []
    var events: [String] { lock.withLock { _events } }
    func record(_ event: String) { lock.withLock { _events.append(event) } }
}

struct JournalingSink: DecodedAudioSink {
    var inner: CollectingSink
    let journal: SinkJournal
    var onAppend: (@Sendable (Int) -> Void)?

    mutating func append(_ chunk: DecodedChunk) throws {
        journal.record("append")
        onAppend?(inner.chunkSizes.count)
        try inner.append(chunk)
    }

    mutating func finish() throws -> CollectedAudio {
        journal.record("finish")
        return try inner.finish()
    }

    mutating func abandon() {
        journal.record("abandon")
        inner = CollectingSink(channelCount: inner.channelCount)
    }
}

// MARK: - Decoding helpers

func makeDecoder(chunkFrames: Int = 16_384, io: any SourceIO = SystemSourceIO(), content: any SourceContentIO = SystemSourceContentIO(), ledger: SecurityScopeLedger = SecurityScopeLedger()) -> SourceDecoder {
    SourceDecoder(access: SourceAccessContext(io: io, ledger: ledger), content: content, configuration: .init(chunkFrames: chunkFrames))
}

func decodeAll(_ url: URL, chunkFrames: Int = 16_384, io: any SourceIO = SystemSourceIO(), content: any SourceContentIO = SystemSourceContentIO()) async throws(DecodeFailure) -> DecodedSource<CollectedAudio> {
    let source = SourceID()
    let decoded = try await makeDecoder(chunkFrames: chunkFrames, io: io, content: content).decode(url, source: source) { interpretation in
        CollectingSink(channelCount: interpretation.channelCount, maximumChunk: chunkFrames)
    }
    #expect(decoded.interpretation.source == source, "the descriptor names the logical source it was asked to decode")
    return decoded
}

func decodeFailure(_ url: URL, chunkFrames: Int = 4096, io: any SourceIO = SystemSourceIO(), content: any SourceContentIO = SystemSourceContentIO()) async -> DecodeFailure? {
    do {
        _ = try await decodeAll(url, chunkFrames: chunkFrames, io: io, content: content)
        return nil
    } catch {
        return error
    }
}

// MARK: - Metadata gateway double

/// Delegates to the system metadata gateway, letting a test rewrite what it reports.
final class AdjustableIO: SourceIO, @unchecked Sendable {
    private let base = SystemSourceIO()
    private let lock = NSLock()
    private var _adjust: (@Sendable (inout MetadataResult, Int) -> Void)?
    private var calls = 0
    private var _starts = 0
    private var _stops = 0

    var provenance: ObservationProvenance { .simulated }
    var metadataCalls: Int { lock.withLock { calls } }
    var scopeBalance: (starts: Int, stops: Int) { lock.withLock { (_starts, _stops) } }

    init(_ adjust: (@Sendable (inout MetadataResult, Int) -> Void)? = nil) { _adjust = adjust }

    func metadata(at url: URL) -> MetadataResult {
        var result = base.metadata(at: url)
        let (adjust, index): ((@Sendable (inout MetadataResult, Int) -> Void)?, Int) = lock.withLock {
            calls += 1
            return (_adjust, calls - 1)
        }
        adjust?(&result, index)
        return result
    }

    func listItems(under directory: URL) -> DirectoryListing { base.listItems(under: directory) }
    func makeReadOnlyBookmark(for url: URL) throws -> Data { try base.makeReadOnlyBookmark(for: url) }
    func resolveBookmark(_ data: Data) -> BookmarkResolution { base.resolveBookmark(data) }
    func startAccessingSecurityScope(_ url: URL) -> Bool {
        lock.withLock { _starts += 1 }
        return true
    }
    func stopAccessingSecurityScope(_ url: URL) { lock.withLock { _stops += 1 } }
    func requestDownload(of url: URL) throws { Issue.record("decode must never request a download") }
    func downloadFraction(of url: URL) async -> Knowledge<Double> { .unknown }
}

extension MetadataResult {
    mutating func modify(_ body: (inout SourceMetadata) -> Void) {
        guard case var .success(metadata) = self else { return }
        body(&metadata)
        self = .success(metadata)
    }
}
