import CryptoKit
import XCTest

/// M1-REF-020 sandboxed grant / relaunch / regrant / relink on the native app (grant A), with the real
/// source engine (not the fixture engine) and synthetic placeholder files only (generated bytes with audio
/// extensions; M1 never reads their content).
///
/// One cycle = 4 GUI scenarios on fresh files and a fresh show:
///   1. **grant**: File › Import Sources… → sandboxed NSOpenPanel (powerbox) → folder → Import Review → Import.
///   2. **relaunch**: quit, relaunch, reopen: the device-local bookmark resolves (no "Needs permission").
///   3. **regrant**: relaunch with `-WWUITestResetSourceAccess YES` (no device-local records, as on another
///      Mac) → "Needs permission" → Source › Grant Access… → panel → identity comparison → Ready.
///   4. **relink**: the file is moved by the harness → status recorded → Source › Relink Source… → panel →
///      comparison → confirm → Ready.
/// Every scenario checks the sources are byte- and mtime-unchanged (zero source writes).
/// `TEST_RUNNER_WW_HOLDOUT_SCENARIOS` / 4 cycles run (default 1 cycle = calibration; 20 = 5 cycles).
@MainActor
final class SourceGrantHoldoutUITests: XCTestCase {
    private var app: XCUIApplication!
    private var workDirectory: URL!
    private var failures: [String] = []
    private var records: [[String: Any]] = []

    override func setUp() async throws {
        continueAfterFailure = true
        guard ProcessInfo.processInfo.environment["WW_PROBE"] != nil else {
            throw XCTSkip("WW_PROBE is not set; run scripts/test.sh --ui")
        }
        workDirectory = FileManager.default.temporaryDirectory
            .appending(path: "WaveWranglerREF020-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: workDirectory, withIntermediateDirectories: true)
    }

    override func tearDown() async throws {
        if let app, app.state != .notRunning { app.terminate() }
        if let workDirectory { try? FileManager.default.removeItem(at: workDirectory) }
    }

    func testGrantRelaunchRegrantRelink() throws {
        let scenarios = Acceptance.count("WW_HOLDOUT_SCENARIOS", default: 4)
        let cycles = max(1, (scenarios + 3) / 4)
        for cycle in 0..<cycles {
            do { try runCycle(cycle) } catch { record(cycle, "cycle", ["threw \(error)"]) }
            if let app, app.state != .notRunning { app.terminate() }
        }
        let passed = records.filter { $0["passed"] as? Bool == true }.count
        Acceptance.writeEvidence("ref020-native-grant", [
            "revision": Acceptance.revision(), "scenarios": records, "executed": records.count, "passed": passed,
        ], test: self)
        for record in records where record["passed"] as? Bool != true {
            XCTFail("REF-020 \(record["cycle"] ?? "?") \(record["scenario"] ?? ""): \(record["failures"] ?? "")")
        }
    }

    // MARK: - Cycle

    private func runCycle(_ cycle: Int) throws {
        let folder = workDirectory.appending(path: "Recorder\(cycle)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let names = ["ref020-\(cycle)-a.wav", "ref020-\(cycle)-b.wav"]
        for (index, name) in names.enumerated() {
            try Data((0..<4096).map { UInt8(truncatingIfNeeded: $0 &* (index + 7)) }).write(to: folder.appending(path: name))
        }
        let document = workDirectory.appending(path: "Grant \(cycle).wwshow")
        try probe(["create", "--file", document.path, "--seed", "\(cycle + 1)"])
        var fingerprints = try fingerprint(folder)

        // 1. Grant through the sandboxed open panel.
        failures = []
        try launchAndOpen(document, extra: [])
        app.typeKey("i", modifierFlags: [.command, .shift])
        choosePath(folder.path, confirm: true)
        let review = element("ww.import.review")
        check(review.waitForExistence(timeout: 10), "Import Review shown")
        Acceptance.record(self, "REF-020 review: \(element("ww.import.confirm").exists ? element("ww.import.confirm").label : "not shown")")
        if review.exists { app.typeKey(.return, modifierFlags: []) }
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names).count == names.count }, "imported rows present: \(statuses(names))")
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names).values.allSatisfy { $0.hasPrefix("Ready") } }, "granted sources Ready: \(statuses(names))")
        check(try fingerprint(folder) == fingerprints, "zero source writes")
        record(cycle, "grant", failures, statuses(names))

        // 2. Relaunch: bookmarks resolve.
        failures = []
        app.typeKey("q", modifierFlags: .command)
        if app.sheets.firstMatch.waitForExistence(timeout: 2) { app.sheets.firstMatch.buttons["Save"].click() }
        check(app.wait(for: .notRunning, timeout: 10), "quit")
        try launchAndOpen(document, extra: [])
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names).values.allSatisfy { $0.hasPrefix("Ready") } && self.statuses(names).count == names.count },
              "after relaunch the bookmarks resolve: \(statuses(names))")
        check(try fingerprint(folder) == fingerprints, "zero source writes")
        record(cycle, "relaunch", failures, statuses(names))

        // 3. Regrant: no device-local access records.
        failures = []
        app.terminate()
        try launchAndOpen(document, extra: ["-WWUITestResetSourceAccess", "YES"])
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names)[names[0]]?.contains("permission") == true },
              "without a record the source needs permission (never Not found): \(statuses(names))")
        // Regrant "b" (row clicks on the first row under the group header don't select reliably in XCUITest).
        select(names[1])
        Acceptance.record(self, "REF-020 before Grant Access: outline \(app.outlines["ww.setup.sources"].value ?? "nil"), inspector access \(element("ww.inspector.access").exists ? "\(element("ww.inspector.access").value ?? "nil")" : "not shown")")
        var granted = menu("Source", "Grant Access…")
        if !granted {
            // Fallback: the row's context menu (records that the menu-bar item was unavailable).
            let row = app.outlines["ww.setup.sources"].outlineRows.containing(NSPredicate(format: "label CONTAINS %@ OR value CONTAINS %@", names[1], names[1])).firstMatch
            row.rightClick()
            let item = app.menuItems["Grant Access…"].firstMatch
            if item.waitForExistence(timeout: 3), item.isEnabled { item.click(); granted = true } else { app.typeKey(.escape, modifierFlags: []) }
            Acceptance.record(self, "REF-020 context-menu Grant Access… used: \(granted)")
        }
        if granted {
            choosePath(folder.appending(path: names[1]).path, confirm: true)
            confirmRelinkSheet()
        }
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names)[names[1]]?.hasPrefix("Ready") == true }, "regranted source Ready: \(statuses(names))")
        check(try fingerprint(folder) == fingerprints, "zero source writes")
        record(cycle, "regrant", failures, statuses(names))

        // 4. Moved source → relink.
        failures = []
        app.typeKey("q", modifierFlags: .command)
        if app.sheets.firstMatch.waitForExistence(timeout: 2) { app.sheets.firstMatch.buttons["Save"].click() }
        _ = app.wait(for: .notRunning, timeout: 10)
        let moved = workDirectory.appending(path: "Moved\(cycle)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: moved, withIntermediateDirectories: true)
        try FileManager.default.moveItem(at: folder.appending(path: names[1]), to: moved.appending(path: names[1]))
        fingerprints = try fingerprint(folder).merging(try fingerprint(moved)) { $1 }
        try launchAndOpen(document, extra: [])
        Thread.sleep(forTimeInterval: 2)
        let afterMove = statuses(names)[names[1]] ?? "missing"
        Acceptance.record(self, "REF-020 status after the harness moved \(names[1]): \(afterMove)")
        select(names[1])
        if menu("Source", "Relink Source…") {
            choosePath(moved.appending(path: names[1]).path, confirm: true)
            confirmRelinkSheet()
        }
        check(Acceptance.waitFor(timeout: 10) { self.statuses(names)[names[1]]?.hasPrefix("Ready") == true }, "relinked source Ready: \(statuses(names))")
        check(try fingerprint(folder).merging(try fingerprint(moved)) { $1 } == fingerprints, "zero source writes")
        record(cycle, "relink (moved: \(afterMove))", failures, statuses(names))
        app.typeKey("q", modifierFlags: .command)
        if app.sheets.firstMatch.waitForExistence(timeout: 2) { app.sheets.firstMatch.buttons["Save"].click() }
    }

    // MARK: - Helpers

    private func record(_ cycle: Int, _ scenario: String, _ failures: [String], _ statuses: [String: String] = [:]) {
        records.append(["cycle": cycle + 1, "scenario": scenario, "passed": failures.isEmpty, "failures": failures, "statuses": statuses])
        Acceptance.record(self, "REF-020 cycle \(cycle + 1) \(scenario): \(failures.isEmpty ? "PASS" : "FAIL \(failures)") \(statuses)")
    }

    private func check(_ condition: @autoclosure () throws -> Bool, _ message: @autoclosure () -> String) {
        if (try? condition()) != true { failures.append(message()) }
    }

    private func launchAndOpen(_ document: URL, extra: [String]) throws {
        app = XCUIApplication()
        app.launchArguments = ["-ApplePersistenceIgnoreState", "YES", "-WWUITestHooks", "YES", "-WWUITestAutosave", "ON",
                               "-WWUITestCenterWindows", "YES"] + extra
        app.launch()
        app.open(document)
        let window = app.windows.matching(identifier: "ww.show.window").firstMatch
        guard window.waitForExistence(timeout: 10) else {
            throw NSError(domain: "REF020", code: 1, userInfo: [NSLocalizedDescriptionKey: "show window did not open"])
        }
        window.typeKey("1", modifierFlags: .command)
        _ = element("ww.setup.sources").waitForExistence(timeout: 10)
    }

    /// In the open panel (a sheet): Go to Folder (⇧⌘G), type the path, Return; then Return to confirm.
    private func choosePath(_ path: String, confirm: Bool) {
        // The sandboxed open panel is drawn by the out-of-process panel service (powerbox); the app's own AX
        // snapshot stalls while it is up, so keys go to the service.
        let service = XCUIApplication(bundleIdentifier: "com.apple.appkit.xpc.openAndSavePanelService")
        Thread.sleep(forTimeInterval: 2.0)
        guard service.state != .notRunning || app.sheets.firstMatch.exists else {
            failures.append("open panel shown")
            return
        }
        let target: XCUIApplication = service.state == .notRunning ? app : service
        Acceptance.record(self, "REF-020 panel host: \(target === service ? "openAndSavePanelService" : "app")")
        target.typeKey("g", modifierFlags: [.command, .shift])
        Thread.sleep(forTimeInterval: 1.0)
        target.typeText(path)
        Thread.sleep(forTimeInterval: 0.5)
        target.typeKey(.return, modifierFlags: [])
        Thread.sleep(forTimeInterval: 1.5)
        if confirm { target.typeKey(.return, modifierFlags: []) }
        Thread.sleep(forTimeInterval: 1.5)
    }

    private func confirmRelinkSheet() {
        let sheet = element("ww.relink.sheet")
        guard sheet.waitForExistence(timeout: 10) else { failures.append("identity comparison sheet shown"); return }
        Acceptance.record(self, "REF-020 comparison: \(element("ww.relink.headline").value ?? element("ww.relink.headline").label)")
        let acknowledge = element("ww.relink.acknowledge")
        if acknowledge.exists { acknowledge.click() }
        let confirm = element("ww.relink.confirm")
        if confirm.exists, confirm.isEnabled { confirm.click() } else { failures.append("confirm enabled in the comparison sheet") }
    }

    private func element(_ identifier: String) -> XCUIElement {
        app.descendants(matching: .any).matching(identifier: identifier).firstMatch
    }

    @discardableResult
    private func menu(_ bar: String, _ title: String) -> Bool {
        app.menuBars.menuBarItems[bar].click()
        let item = app.menuBars.menuBarItems[bar].menuItems[title]
        guard item.waitForExistence(timeout: 3), item.isEnabled else {
            failures.append("\(bar) › \(title) available")
            app.typeKey(.escape, modifierFlags: [])
            return false
        }
        item.click()
        return true
    }

    /// Status values of the Sources rows whose name is in `names`.
    private func statuses(_ names: [String]) -> [String: String] {
        var result: [String: String] = [:]
        let rows = app.outlines["ww.setup.sources"].outlineRows.allElementsBoundByIndex
        for row in rows {
            let name = row.descendants(matching: .any).matching(NSPredicate(format: "identifier BEGINSWITH 'ww.setup.source.' AND NOT identifier ENDSWITH '.status'")).firstMatch
            let label = (name.value as? String).flatMap { $0.isEmpty ? nil : $0 } ?? name.label
            guard let match = names.first(where: { label.contains($0) }) else { continue }
            let status = row.descendants(matching: .any).matching(NSPredicate(format: "identifier ENDSWITH '.status'")).firstMatch
            result[match] = status.value as? String ?? ""
        }
        return result
    }

    private func select(_ name: String) {
        let row = app.outlines["ww.setup.sources"].outlineRows.containing(NSPredicate(format: "label CONTAINS %@ OR value CONTAINS %@", name, name)).firstMatch
        guard row.waitForExistence(timeout: 5) else { failures.append("row \(name)"); return }
        let outline = app.outlines["ww.setup.sources"]
        for offset in [0.03, 0.15, 0.3, 0.03] {
            row.coordinate(withNormalizedOffset: CGVector(dx: offset, dy: 0.5)).click()
            if Acceptance.waitFor(timeout: 2, { (outline.value as? String) == "1 selected" }) { return }
        }
        failures.append("selected \(name): \(outline.value ?? "nil")")
    }

    private func probe(_ arguments: [String]) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: ProcessInfo.processInfo.environment["WW_PROBE"]!)
        process.arguments = arguments
        process.standardOutput = FileHandle.nullDevice
        try process.run()
        process.waitUntilExit()
    }

    /// name → sha256 + modification date for every file in `folder`.
    private func fingerprint(_ folder: URL) throws -> [String: String] {
        var result: [String: String] = [:]
        for name in try FileManager.default.contentsOfDirectory(atPath: folder.path) {
            let url = folder.appending(path: name)
            let digest = SHA256.hash(data: try Data(contentsOf: url)).map { String(format: "%02x", $0) }.joined()
            let modified = (try FileManager.default.attributesOfItem(atPath: url.path)[.modificationDate] as? Date)?.timeIntervalSince1970 ?? 0
            result[name] = "\(digest)@\(modified)"
        }
        return result
    }
}
